Style/Encoding:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 80

AbcSize:
  Exclude:
    - 'lib/akira/dataexchange.rb'

# Disable metrics bellow once the library is cleaned up

AbcSize:
  Enabled: false

Style/Next:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
